lista_preguntas = [
    {"pregunta": "¿Cuál es el océano más grande del mundo?", "respuesta_1": "Atlántico", "respuesta_2": "Pacífico", "respuesta_3": "Índico", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué planeta es conocido como el planeta rojo?", "respuesta_1": "Venus", "respuesta_2": "Marte", "respuesta_3": "Júpiter", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Quién escribió 'Cien años de soledad'?", "respuesta_1": "Pablo Neruda", "respuesta_2": "Gabriel García Márquez", "respuesta_3": "Mario Vargas Llosa", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Cuántos continentes hay en el mundo?", "respuesta_1": "5", "respuesta_2": "6", "respuesta_3": "7", "respuesta_correcta": 3, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Cuál es el país más grande del mundo?", "respuesta_1": "China", "respuesta_2": "Estados Unidos", "respuesta_3": "Rusia", "respuesta_correcta": 3, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿En qué país se encuentra la Torre Eiffel?", "respuesta_1": "Italia", "respuesta_2": "Francia", "respuesta_3": "España", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué gas respiramos que es esencial para la vida?", "respuesta_1": "Oxígeno", "respuesta_2": "Nitrógeno", "respuesta_3": "Dióxido de carbono", "respuesta_correcta": 1, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Quién pintó la Mona Lisa?", "respuesta_1": "Vincent Van Gogh", "respuesta_2": "Leonardo da Vinci", "respuesta_3": "Pablo Picasso", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Cuál es el río más largo del mundo?", "respuesta_1": "Nilo", "respuesta_2": "Amazonas", "respuesta_3": "Yangtsé", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué instrumento tiene teclas blancas y negras?", "respuesta_1": "Violín", "respuesta_2": "Piano", "respuesta_3": "Guitarra", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Cuál es el animal terrestre más rápido?", "respuesta_1": "Leopardo", "respuesta_2": "Tigre", "respuesta_3": "Guepardo", "respuesta_correcta": 3, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué país tiene forma de bota?", "respuesta_1": "México", "respuesta_2": "Italia", "respuesta_3": "Brasil", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué día se celebra la independencia de Argentina?", "respuesta_1": "9 de julio", "respuesta_2": "25 de mayo", "respuesta_3": "20 de junio", "respuesta_correcta": 1, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Quién fue el primer hombre en pisar la Luna?", "respuesta_1": "Yuri Gagarin", "respuesta_2": "Neil Armstrong", "respuesta_3": "Buzz Aldrin", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué idioma se habla en Brasil?", "respuesta_1": "Portugués", "respuesta_2": "Español", "respuesta_3": "Inglés", "respuesta_correcta": 1, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Cuál es el metal más valioso del mundo?", "respuesta_1": "Oro", "respuesta_2": "Platino", "respuesta_3": "Rodio", "respuesta_correcta": 3, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Cuál es la capital de Japón?", "respuesta_1": "Pekín", "respuesta_2": "Tokio", "respuesta_3": "Seúl", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué número es el resultado de 7 x 8?", "respuesta_1": "56", "respuesta_2": "54", "respuesta_3": "64", "respuesta_correcta": 1, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué deporte practica Lionel Messi?", "respuesta_1": "Básquet", "respuesta_2": "Tenis", "respuesta_3": "Fútbol", "respuesta_correcta": 3, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué hueso protege el cerebro?", "respuesta_1": "Costillas", "respuesta_2": "Cráneo", "respuesta_3": "Fémur", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Cuál es el país con mayor población del mundo?", "respuesta_1": "India", "respuesta_2": "China", "respuesta_3": "Estados Unidos", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Cuál es el símbolo químico del agua?", "respuesta_1": "O2", "respuesta_2": "H2O", "respuesta_3": "CO2", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué animal pone huevos?", "respuesta_1": "Perro", "respuesta_2": "Gallina", "respuesta_3": "Gato", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué es un triángulo?", "respuesta_1": "Figura con 4 lados", "respuesta_2": "Figura con 3 lados", "respuesta_3": "Figura con 5 lados", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué se usa para escribir en una pizarra?", "respuesta_1": "Lapicera", "respuesta_2": "Tiza", "respuesta_3": "Crayón", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué planeta es el más cercano al Sol?", "respuesta_1": "Venus", "respuesta_2": "Tierra", "respuesta_3": "Mercurio", "respuesta_correcta": 3, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué continente es conocido como el viejo continente?", "respuesta_1": "Asia", "respuesta_2": "Europa", "respuesta_3": "África", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué órgano bombea sangre en el cuerpo?", "respuesta_1": "Pulmones", "respuesta_2": "Corazón", "respuesta_3": "Estómago", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Quién descubrió América?", "respuesta_1": "Simón Bolívar", "respuesta_2": "Cristóbal Colón", "respuesta_3": "Hernán Cortés", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Cuántos colores tiene el arco iris?", "respuesta_1": "7", "respuesta_2": "6", "respuesta_3": "8", "respuesta_correcta": 1, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué país tiene una bandera roja con una estrella amarilla?", "respuesta_1": "Japón", "respuesta_2": "Vietnam", "respuesta_3": "China", "respuesta_correcta": 3, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué animal es conocido por su gran memoria?", "respuesta_1": "Elefante", "respuesta_2": "Perro", "respuesta_3": "Gato", "respuesta_correcta": 1, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Cuál es la capital de España?", "respuesta_1": "Madrid", "respuesta_2": "Barcelona", "respuesta_3": "Sevilla", "respuesta_correcta": 1, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué materia estudia los números?", "respuesta_1": "Historia", "respuesta_2": "Matemática", "respuesta_3": "Lengua", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Cuál es el mamífero más grande?", "respuesta_1": "Ballena azul", "respuesta_2": "Elefante africano", "respuesta_3": "Hipopótamo", "respuesta_correcta": 1, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué gas exhalamos al respirar?", "respuesta_1": "Oxígeno", "respuesta_2": "Hidrógeno", "respuesta_3": "Dióxido de carbono", "respuesta_correcta": 3, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué día se celebra la Navidad?", "respuesta_1": "24 de diciembre", "respuesta_2": "25 de diciembre", "respuesta_3": "1 de enero", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué instrumento tiene cuerdas?", "respuesta_1": "Flauta", "respuesta_2": "Batería", "respuesta_3": "Guitarra", "respuesta_correcta": 3, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué país ganó el Mundial 2022?", "respuesta_1": "Francia", "respuesta_2": "Argentina", "respuesta_3": "Brasil", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Cuál es el órgano principal del sistema nervioso?", "respuesta_1": "Hígado", "respuesta_2": "Cerebro", "respuesta_3": "Estómago", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué color resulta de mezclar rojo y amarillo?", "respuesta_1": "Naranja", "respuesta_2": "Verde", "respuesta_3": "Violeta", "respuesta_correcta": 1, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué estación sigue al invierno?", "respuesta_1": "Primavera", "respuesta_2": "Verano", "respuesta_3": "Otoño", "respuesta_correcta": 1, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Cuál es el país de origen del sushi?", "respuesta_1": "China", "respuesta_2": "Japón", "respuesta_3": "Corea", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué unidad se usa para medir la temperatura?", "respuesta_1": "Voltios", "respuesta_2": "Metros", "respuesta_3": "Grados Celsius", "respuesta_correcta": 3, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Cuál es el país más pequeño del mundo?", "respuesta_1": "San Marino", "respuesta_2": "Mónaco", "respuesta_3": "Ciudad del Vaticano", "respuesta_correcta": 3, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué animal es el rey de la selva?", "respuesta_1": "Tigre", "respuesta_2": "León", "respuesta_3": "Jaguar", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué fruta es amarilla por fuera y blanca por dentro?", "respuesta_1": "Pera", "respuesta_2": "Banana", "respuesta_3": "Manzana", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué invento permitió la impresión de libros?", "respuesta_1": "Teléfono", "respuesta_2": "Imprenta", "respuesta_3": "Computadora", "respuesta_correcta": 2, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Cuántos segundos tiene un minuto?", "respuesta_1": "60", "respuesta_2": "100", "respuesta_3": "90", "respuesta_correcta": 1, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
    {"pregunta": "¿Qué planeta tiene un anillo a su alrededor?", "respuesta_1": "Saturno", "respuesta_2": "Urano", "respuesta_3": "Neptuno", "respuesta_correcta": 1, "aciertos": 0, "fallos": 0, "veces_preguntada": 0},
]

lista_preguntas_dificiles = [
    {"pregunta": "¿Cuál es el elemento químico con el número atómico 79?", "respuesta_1": "Plata", "respuesta_2": "Oro", "respuesta_3": "Cobre", "respuesta_correcta": 2},
    {"pregunta": "¿Quién escribió 'La Divina Comedia'?", "respuesta_1": "Dante Alighieri", "respuesta_2": "William Shakespeare", "respuesta_3": "Homero", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es la capital de Mongolia?", "respuesta_1": "Ulán Bator", "respuesta_2": "Astana", "respuesta_3": "Bakú", "respuesta_correcta": 1},
    {"pregunta": "¿Qué país tiene el mayor número de volcanes activos del mundo?", "respuesta_1": "Indonesia", "respuesta_2": "Japón", "respuesta_3": "Chile", "respuesta_correcta": 1},
    {"pregunta": "¿Quién fue el autor de la teoría del electromagnetismo?", "respuesta_1": "Isaac Newton", "respuesta_2": "James Clerk Maxwell", "respuesta_3": "Nikola Tesla", "respuesta_correcta": 2},
    {"pregunta": "¿Qué filósofo dijo 'Solo sé que no sé nada'?", "respuesta_1": "Platón", "respuesta_2": "Aristóteles", "respuesta_3": "Sócrates", "respuesta_correcta": 3},
    {"pregunta": "¿Cuál es el idioma oficial de Irán?", "respuesta_1": "Árabe", "respuesta_2": "Pastún", "respuesta_3": "Persa", "respuesta_correcta": 3},
    {"pregunta": "¿Qué país abolió la esclavitud primero?", "respuesta_1": "Gran Bretaña", "respuesta_2": "Francia", "respuesta_3": "Haití", "respuesta_correcta": 3},
    {"pregunta": "¿Cuál es la fórmula química del ácido sulfúrico?", "respuesta_1": "HCl", "respuesta_2": "H2SO4", "respuesta_3": "HNO3", "respuesta_correcta": 2},
    {"pregunta": "¿Qué pintor es famoso por cortarse una oreja?", "respuesta_1": "Monet", "respuesta_2": "Van Gogh", "respuesta_3": "Goya", "respuesta_correcta": 2},
    {"pregunta": "¿En qué año comenzó la Segunda Guerra Mundial?", "respuesta_1": "1937", "respuesta_2": "1939", "respuesta_3": "1941", "respuesta_correcta": 2},
    {"pregunta": "¿Qué instrumento mide los terremotos?", "respuesta_1": "Termómetro", "respuesta_2": "Sismógrafo", "respuesta_3": "Barómetro", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es el hueso más largo del cuerpo humano?", "respuesta_1": "Fémur", "respuesta_2": "Húmero", "respuesta_3": "Tibia", "respuesta_correcta": 1},
    {"pregunta": "¿Qué país tiene la mayor reserva de petróleo del mundo?", "respuesta_1": "Arabia Saudita", "respuesta_2": "Venezuela", "respuesta_3": "Irak", "respuesta_correcta": 2},
    {"pregunta": "¿Qué científico formuló las leyes del movimiento?", "respuesta_1": "Einstein", "respuesta_2": "Newton", "respuesta_3": "Galileo", "respuesta_correcta": 2},
    {"pregunta": "¿Qué planeta tiene el día más largo?", "respuesta_1": "Mercurio", "respuesta_2": "Venus", "respuesta_3": "Urano", "respuesta_correcta": 2},
    {"pregunta": "¿Qué rey francés fue conocido como el Rey Sol?", "respuesta_1": "Luis XIV", "respuesta_2": "Luis XVI", "respuesta_3": "Carlos V", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es el nombre del satélite natural de Marte?", "respuesta_1": "Titán", "respuesta_2": "Fobos", "respuesta_3": "Ganímedes", "respuesta_correcta": 2},
    {"pregunta": "¿Quién descubrió la penicilina?", "respuesta_1": "Louis Pasteur", "respuesta_2": "Alexander Fleming", "respuesta_3": "Marie Curie", "respuesta_correcta": 2},
    {"pregunta": "¿Qué país tiene más Patrimonios de la Humanidad?", "respuesta_1": "Francia", "respuesta_2": "China", "respuesta_3": "Italia", "respuesta_correcta": 3},
    {"pregunta": "¿Qué famoso físico escribió 'Breve historia del tiempo'?", "respuesta_1": "Stephen Hawking", "respuesta_2": "Richard Feynman", "respuesta_3": "Carl Sagan", "respuesta_correcta": 1},
    {"pregunta": "¿En qué país nació Nikola Tesla?", "respuesta_1": "Austria", "respuesta_2": "Serbia", "respuesta_3": "Croacia", "respuesta_correcta": 3},
    {"pregunta": "¿Qué río atraviesa París?", "respuesta_1": "Tíber", "respuesta_2": "Sena", "respuesta_3": "Danubio", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es la capital de Nigeria?", "respuesta_1": "Abuja", "respuesta_2": "Lagos", "respuesta_3": "Accra", "respuesta_correcta": 1},
    {"pregunta": "¿Qué compositor quedó sordo?", "respuesta_1": "Beethoven", "respuesta_2": "Mozart", "respuesta_3": "Bach", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es el símbolo del tungsteno?", "respuesta_1": "W", "respuesta_2": "Tg", "respuesta_3": "Tu", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es la estrella más cercana a la Tierra después del Sol?", "respuesta_1": "Sirius", "respuesta_2": "Alfa Centauri", "respuesta_3": "Betelgeuse", "respuesta_correcta": 2},
    {"pregunta": "¿Qué escritor argentino ganó el Premio Cervantes?", "respuesta_1": "Julio Cortázar", "respuesta_2": "Borges", "respuesta_3": "Juan Gelman", "respuesta_correcta": 3},
    {"pregunta": "¿Qué civilización construyó Machu Picchu?", "respuesta_1": "Azteca", "respuesta_2": "Maya", "respuesta_3": "Inca", "respuesta_correcta": 3},
    {"pregunta": "¿Cuál es el país más joven del mundo?", "respuesta_1": "Kosovo", "respuesta_2": "Sudán del Sur", "respuesta_3": "Timor Oriental", "respuesta_correcta": 2}
]